#!/bin/sh
cd cchecker-server-docker
docker build -t docker_server .
cd ..
cd cchecker-ui-docker
docker build -t docker_ui .
cd ..

if [[ $(docker inspect --format="{{.Id}}" cchecker-ui) ]]; then
  docker kill cchecker-ui
  docker start  cchecker-ui
else
  docker run --name cchecker-ui -d -p 80:80 --net=host docker_ui
fi

if [[ $(docker inspect --format="{{.Id}}" cchecker-gateway) ]]; then
  docker kill cchecker-gateway
  docker start -a cchecker-gateway
else
  docker run -e "db_driver=$db_driver" -e "db_user=$db_user" -e "db_credential=$db_credential" -e "db_url=$db_url" --name cchecker-gateway -p 8080:8080 --net=host docker_server

fi
