version: '2'
services:
  ui:
    container_name: cchecker-ui
    build: ./cchecker-ui-docker
    ports:
     - "8081:80"
    environment:
      REST_API: $REST_API
      configuration: $configuration
    networks:
      app_net:
        ipv4_address: 172.16.239.10
  server:
    container_name: cchecker-gateway
    build: ./cchecker-server-docker
    ports:
     - "8080:8080"
     - "8082:8082"
    networks:
      app_net:
        ipv4_address: 172.16.239.11
    environment:
      cdetier: $cdetier
      LANG: $LANG
      db_driver: $db_driver
      db_url: $db_url
      db_user: $db_user
      db_credential: $db_credential
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.239.0/24
