#!/bin/sh
docker-compose stop
if [ $1 ]; then
  while [ -n "$1" ]; do # while loop starts

    case "$1" in

    -f) echo "docker-compose -f $2 up" ;;

    esac

    shift

  done
else
  docker-compose up
fi
